# Generated by Django 4.2.7 on 2023-11-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=20)),
                ('eventName', models.CharField(max_length=200)),
                ('localDate', models.DateTimeField()),
                ('localTime', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('imageLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=2000)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketMaster.event')),
            ],
        ),
    ]
