# Generated by Django 4.2.7 on 2023-11-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='localDate',
            new_name='localDateTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='localTime',
        ),
    ]
