# Generated by Django 4.2.7 on 2023-12-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketMaster', '0002_remove_event_localdatetime_event_citystate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starRating',
            field=models.IntegerField(default=-1),
        ),
    ]
