# Generated by Django 4.2.7 on 2023-12-06 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketMaster', '0003_alter_comment_starrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starRating',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
