# Generated by Django 4.2.7 on 2023-11-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketMaster', '0004_alter_comments_user_alter_savedevents_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
